# Generated by Django 3.1 on 2023-05-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_auto_20230520_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
