# Generated by Django 3.1 on 2023-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_auto_20230525_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=20, max_length=20),
        ),
    ]
