# Generated by Django 3.1 on 2023-06-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0005_auto_20230601_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
